# Uncomment this line to define a global platform for your project
 platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'Smartisan-Notes' do
pod ‘IBAnimatable’
end

target 'Smartisan-NotesTests' do

end

target 'Smartisan-NotesUITests' do

end

